# port
server:
  port: 10086
# Eureka service name
spring:
  application:
    name: eureka-server
# put EurekaServer in service list, default to true
eureka:
  client:
    register-with-eureka: false
    # fetch registry list, default to true
    fetch-registry: false
    # EurekaServer address
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
logging:
  # pattern:
  #   file: ".%d{yyyy-MM-dd}.log"
  #   console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    path: "./logs/"
    name: "./logs/${spring.application.name}.log"
  level:
    root: INFO
  logback:
    rollingpolicy:
      file-name-pattern: "./${LOG_PATH}/${spring.application.name}-%d{yyyy-MM-dd-HH}.%i.log"
      max-file-size: 10MB
      max-history: 72
